### ISSUE TITLE
The Code is shown in the blog content

### ISSUE THREAD

**Issue by RushabhBhalgat** [TheAbhijeet/Django_blog#4]
![issue](https://user-images.githubusercontent.com/65655146/87298715-45490b00-c528-11ea-863c-c8bd85261ea5.png)

**Comment by lovemm9** [comment]
just add |safe| after post.content in index.html

**Comment by shivstha** [comment]
`<p class="card-text">{{post.content|safe|truncatewords:200 }}</p>`
